"use client"
import Footer from '@/components/footer/Footer';
import Navbar from "@/components/Navbar";
import 'wowjs/css/libs/animate.css';
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect } from 'react';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Easygorooms Hospitality :: One Stop Solution For Hotels -',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
    import('preline')
  }, [])
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/fav.png'/>
      </head>
      <body className={inter.className}> 
      <Navbar/>
      {children}
      <Footer/>
    
      </body>
    </html>
  )
}
